---
- name: collect and print ldap account password information (pw exipiry in days)
  hosts: localhost
  vars:
    uid: ['list', 'of', 'your', 'ldap', 'users']
  tasks:
  - name: loop through the account uids and collect pw info
    shell: ldapsearch -x -H ldap://yourLdapServer -b "uid={{ item }},ou=blah,dc=blah,dc=blah" passwordexpirationtime | grep -v ^# | grep password | cut -d':' -f2 | cut -d' ' -f2 |cut -c -8 | sed 's/\(....\)\(..\)/\1-\2-/'
    with_items:
    - "{{ uid }}"
    register: uidvar
 
  - name: convert date returned from passwordexpirationtime and compare to todays date
    shell: "if [[ $(( ($(date +%s) - $(date -d 2018-06-09 +%s)) / 86400 )) -gt 0 ]]; then echo {{ item.1 }} account password EXPIRED $(( ($(date +%s) - $(date -d 2018-03-09 +%s)) / 86400 )); else echo {{ item.1 }} account password expires in $(( ($(date +%s) - $(date -d {{ item.0 }} +%s)) / 86400 )) days; fi"
    with_together:
    - "{{ uidvar.results | map(attribute='stdout') | list }}"
    - "{{ uid }}"
    register: acctexpire

  - name: print account expiry status in days
    debug:
      msg: "{{ acctexpire.results | map(attribute='stdout') | list }}" 
