---
- name: convert priv key and insert key value pair into credential template
  hosts: localhost
  vars:
  - priv_key: ['yourPrivKey']
  - cred_tower: ['yourTowerCred.json']
  tasks:
  - name: convert private key
    shell: "cat {{ item }} | grep -v '^-' | xargs | sed -e 's/ /\\n/g' | sed -e 's/^/-----BEGIN RSA PRIVATE KEY-----\\n/g' | sed -e 's/$/\\n-----END RSA PRIVATE KEY-----/g'| sed -e 's/^/"/g' | sed -e 's/$/"/g' | sed -e 's/^/"ssh_key_data":\ /g'  | sed -e 's/^/      /g' > /tmp/{{ item }}.converted"        
    with_items:
    - "{{ priv_key }}"
 
  - name: insert of converted key into json template as a value for the ssh_key_data key
    lineinfile:
      path: "/root/{{ item.0 }}"
      regexp: 'ssh_key_data'
      insertafter: 'ssh_key_data'
      line: "{{ lookup('file', '/tmp/{{ item.1 }}.converted') }}"
    with_together:
    - "{{ cred_tower }}"
    - "{{ priv_key }}"
